# === Infra / Cloud ===
aws:
  - changed-files:
      - any-glob-to-any-file:
          - "infra/**"
          - "terraform/**"
          - "**/*.tf"
          - "**/aws/**"
          - "**/*aws*.md"

terraform:
  - changed-files:
      - any-glob-to-any-file:
          - "terraform/**"
          - "**/*.tf"

opensearch:
  - changed-files:
      - any-glob-to-any-file:
          - "**/opensearch/**"

kafka:
  - changed-files:
      - any-glob-to-any-file:
          - "**/kafka/**"

mongodb:
  - changed-files:
      - any-glob-to-any-file:
          - "**/mongo*/**"
          - "**/*mongo*.md"

# === Containers / K8s ===
docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Dockerfile"
          - "**/*.dockerfile"
          - "**/docker-compose*.yml"
          - "**/docker-compose*.yaml"
          - "**/docker/**"

kubernetes:
  - changed-files:
      - any-glob-to-any-file:
          - "**/k8s/**"
          - "**/kubernetes/**"
          - "**/*.k8s.yaml"
          - "**/*deployment*.yaml"
          - "**/*service*.yaml"

# === Languages / Stacks ===
python:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.py"
          - "**/requirements.txt"
          - "**/pyproject.toml"
          - "**/Pipfile"

javascript:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.js"

typescript:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.ts"
          - "**/*.tsx"

node:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"
          - "pnpm-lock.yaml"
          - "yarn.lock"

react:
  - changed-files:
      - any-glob-to-any-file:
          - "**/src/**"
          - "**/*.tsx"

fastapi:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*fastapi*/**"
          - "**/*.py"

# === CI / Automation ===
github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - "**/.github/**"

# === Security / Scanning ===
security:
  - changed-files:
      - any-glob-to-any-file:
          - "**/.github/workflows/codeql.yml"
          - "**/.github/workflows/tfsec.yml"
          - "**/.github/workflows/trivy.yml"
          - "**/.github/dependabot.yml"
          - "**/.trivyignore"
          - "**/.tfsec*"
          - "CODEOWNERS"
          - "SECURITY.md"

# === Docs / Diagrams / Data ===
docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "doc/**"
          - "docs/**"

diagrams:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.puml"
          - "**/*.plantuml"
          - "**/*.mmd"
          - "**/*.drawio"
          - "**/diagrams/**"

data:
  - changed-files:
      - any-glob-to-any-file:
          - "data/**"
          - "**/*.csv"
          - "**/*.parquet"
          - "**/*.jsonl"

# === Tests / Tooling ===
tests:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*test*/**"
          - "**/*.spec.*"
          - "**/*.test.*"

lint:
  - changed-files:
      - any-glob-to-any-file:
          - "**/.eslintrc*"
          - "**/.prettierrc*"
          - "**/.flake8"
          - "**/pyproject.toml"
          - "**/.ruff.toml"

formatting:
  - changed-files:
      - any-glob-to-any-file:
          - "**/.prettierrc*"
          - "**/.editorconfig"

# === Repo hygiene ===
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package-lock.json"
          - "pnpm-lock.yaml"
          - "yarn.lock"
          - "requirements.txt"
          - "poetry.lock"

changelog:
  - changed-files:
      - any-glob-to-any-file:
          - "CHANGELOG.md"

config:
  - changed-files:
      - any-glob-to-any-file:
          - ".gitattributes"
          - ".gitignore"
          - ".env.example"
          - ".env.*.example"
