# === Infra / Cloud ===
aws:
  - 'infra/**'
  - 'terraform/**'
  - '**/*.tf'
  - '**/aws/**'
  - '**/*aws*.md'
terraform:
  - 'terraform/**'
  - '**/*.tf'
opensearch:
  - '**/opensearch/**'
kafka:
  - '**/kafka/**'
mongodb:
  - '**/mongo*/**'
  - '**/*mongo*.md'

# === Containers / K8s ===
docker:
  - '**/Dockerfile'
  - '**/docker-compose*.yml'
  - '**/docker/**'
kubernetes:
  - '**/k8s/**'
  - '**/*.k8s.yaml'
  - '**/*deployment*.yaml'
  - '**/*service*.yaml'

# === Languages / Stacks ===
python:
  - '**/*.py'
  - '**/requirements.txt'
  - '**/pyproject.toml'
  - '**/Pipfile'
javascript:
  - '**/*.js'
typescript:
  - '**/*.ts'
  - '**/*.tsx'
node:
  - 'package.json'
  - 'package-lock.json'
  - 'pnpm-lock.yaml'
  - 'yarn.lock'
react:
  - '**/src/**'
  - '**/*.tsx'
fastapi:
  - '**/*fastapi*/**'
  - '**/*.py'

# === CI / Automation ===
github-actions:
  - '.github/workflows/**'
ci:
  - '.github/workflows/**'
  - '**/.github/**'

# === Security / Scanning ===
security:
  - '**/.github/workflows/codeql.yml'
  - '**/.github/workflows/tfsec.yml'
  - '**/.github/workflows/trivy.yml'
  - '**/.github/dependabot.yml'
  - '**/.trivyignore'
  - '**/.tfsec*'
  - 'CODEOWNERS'
  - 'SECURITY.md'

# === Docs / Diagrams / Data ===
docs:
  - '**/*.md'
  - 'doc/**'
  - 'docs/**'
diagrams:
  - '**/*.puml'
  - '**/*.plantuml'
  - '**/*.mmd'
  - '**/*.drawio'
  - '**/diagrams/**'
data:
  - 'data/**'
  - '**/*.csv'
  - '**/*.parquet'
  - '**/*.jsonl'

# === Tests / Tooling ===
tests:
  - '**/*test*/**'
  - '**/*.spec.*'
  - '**/*.test.*'
lint:
  - '**/.eslintrc*'
  - '**/.prettierrc*'
  - '**/.flake8'
  - '**/pyproject.toml'
  - '**/.ruff.toml'
formatting:
  - '**/.prettierrc*'
  - '**/.editorconfig'

# === Repo hygiene ===
dependencies:
  - 'package-lock.json'
  - 'pnpm-lock.yaml'
  - 'yarn.lock'
  - 'requirements.txt'
  - 'poetry.lock'
changelog:
  - 'CHANGELOG.md'
config:
  - '.gitattributes'
  - '.gitignore'
  - '.env.example'
  - '.env.*.example'
