name: ChatGPT PR Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  summarize-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PR diff stats
        id: pr-stats
        run: |
          echo "ADDITIONS=${{ github.event.pull_request.additions }}" >> $GITHUB_ENV
          echo "DELETIONS=${{ github.event.pull_request.deletions }}" >> $GITHUB_ENV
          echo "CHANGED_FILES=${{ github.event.pull_request.changed_files }}" >> $GITHUB_ENV

      - name: Select model
        id: model
        run: |
          if [ $ADDITIONS -gt 500 ]; then
            echo "MODEL=gpt-4o" >> $GITHUB_ENV
          else
            echo "MODEL=gpt-4o-mini" >> $GITHUB_ENV
          fi

      - name: Get changed files list
        id: files
        run: |
          gh api repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files \
            --jq '.[].filename' > files.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate PR summary with ChatGPT
        id: summary
        run: |
          FILES=$(cat files.txt | head -n 20 | tr '\n' ', ')
          PROMPT="Summarize this pull request. Focus on purpose, major changes, and impact.\n\nFiles changed:\n$FILES"

          SUMMARY=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"${MODEL}\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"You are a helpful assistant that summarizes GitHub pull requests.\"},
                {\"role\": \"user\", \"content\": \"$PROMPT\"}
              ],
              \"max_tokens\": 300
            }" | jq -r '.choices[0].message.content')

          echo "$SUMMARY" > summary.txt
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Post PR comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('summary.txt', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "🤖 **ChatGPT PR Summary** (model: " + process.env.MODEL + ")\n\n" + body
            });
