# .github/workflows/tfsec.yml
name: tfsec (Terraform IaC)

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: "0 3 * * 1"

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha || github.sha }}

      - name: Install tfsec
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: |
          tfsec . --format sarif --out tfsec.sarif || true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
