name: Trivy Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: "0 4 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  trivy-fs:
    name: Trivy FS/IaC/Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy FS scan → SARIF
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-fs.sarif
          severity: HIGH,CRITICAL
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif

  trivy-sbom:
    name: Trivy SBOM/Deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy deps (sbom) → SARIF
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: repo
          format: sarif
          output: trivy-sbom.sarif
          severity: MEDIUM,HIGH,CRITICAL
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-sbom.sarif
