name: Trivy Security Scan

on:
  # Fork-safe PR context so we can upload SARIF to Code Scanning
  pull_request_target:
    types: [opened, synchronize, reopened]
  # Still scan on pushes to default branches and on schedule
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: "0 4 * * 1"

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  trivy-fs:
    name: Trivy FS/IaC/Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha || github.sha }}

      - name: Trivy FS scan → SARIF
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          exit-code: 0
          ignore-unfixed: true
          format: sarif
          output: trivy-fs.sarif
          severity: HIGH,CRITICAL
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif

  trivy-sbom:
    name: Trivy SBOM/Deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha || github.sha }}

      - name: Trivy deps (sbom) → SARIF
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: repo
          format: sarif
          output: trivy-sbom.sarif
          severity: MEDIUM,HIGH,CRITICAL
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-sbom.sarif
